source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version  
ruby ">= 2.6.10"

# Ruby 3.4 compatibility fixes
gem 'abbrev'

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'

# Fastlane for iOS automation
gem 'fastlane', '~> 2.219'

# Fastlane plugins
gem 'fastlane-plugin-versioning'
gem 'fastlane-plugin-changelog'