name: Mobile iOS Release (App Store)

on:
  push:
    branches: [main]

concurrency:
  group: mobile-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Build and Upload to App Store Connect
    runs-on: macos-latest
    timeout-minutes: 90
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Select Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install JS deps (root)
        run: pnpm install --frozen-lockfile

      - name: Install JS deps (mobile app)
        run: pnpm --dir apps/mobile install --no-frozen-lockfile

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: apps/mobile/ios

      - name: Install iOS pods (with repo update)
        run: |
          cd apps/mobile/ios
          pod install --repo-update

      - name: Match SSH (optional)
        env:
          MATCH_SSH_PRIVATE_KEY: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$MATCH_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to App Store Connect
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: npx nx deploy-production mobile

      - name: Upload Xcode/Gym Logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-gym-logs
          path: |
            ~/Library/Logs/gym/**/*
            ~/Library/Logs/scan/**/*
